Guard against missing machine tags in GS-leaderboards
ref: Sentry BOOGIESTATS-V
```
KeyError: 'machineTag'
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "boogiestats/boogie_api/views.py", line 244, in score_submit
    handle_scores(body_parsed, gs_response, players)
  File "boogiestats/boogie_api/views.py", line 278, in handle_scores
    player_instance.update_name_and_tag(gs_player)
  File "boogiestats/boogie_api/models.py", line 226, in update_name_and_tag
    self.machine_tag = self_entry["machineTag"]
```

```
{
    comments: "68e, 6g",
    date: "2023-06-04 12:31:38",
    isFail: False,
    isRival: False,
    isSelf: True,
    name: "Bakandrev",
    rank: 224,
    score: 9681,
}
```